version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python:
    build: .
    container_name: python_app
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data: